[package]
name = "kwestion"
version = "0.1.0"
edition = "2024"
authors = ["FluxKraken"]
license = "MIT"
description = "A fancy ephemeral textbox input for the terminal."
repository = "https://github.com/FluxKraken/kwestion"

[dependencies]
anyhow = "1.0.104"
crossterm = "0.29.0"
ratatui = { version = "0.30.2", features = ["palette"] }
ratatui-textarea = "0.9.2"
